apiVersion: v1
kind: Node
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: super1
spec: {}
---
apiVersion: v1
kind: Node
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: super2
spec: {}
---
apiVersion: v1
kind: Node
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: super3
spec: {}
---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: Exists
---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: Exists
            # operator: In
            # values:
            # - ""
  storageClassName: localblock
  volumeMode: Block
  fstype: ext4
  maxDeviceCount: 1  # <-- Maximum number of devices per node to be used
  deviceInclusionSpec:
    deviceTypes:
    - disk
      # - part   # if not using partitions
    deviceMechanicalProperties:
    - Rotational   
