apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: noobaa-endpoint
  creationTimestamp: "2022-05-18T13:59:30Z"
  generateName: noobaa-db-pg-
  labels:
    app: noobaa
    controller-revision-hash: noobaa-db-pg-75bb74657
    noobaa-db: postgres
    statefulset.kubernetes.io/pod-name: noobaa-db-pg-0
  name: noobaa-db-pg-0
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: noobaa-db-pg
    uid: f25257ec-2761-4152-a047-47e142f328df
  resourceVersion: "54018"
  uid: 55e24e16-5adb-410b-92fe-4897cddb4d92
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: Exists
  containers:
  - env:
    - name: POSTGRESQL_DATABASE
      value: nbcore
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: noobaa-db
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: noobaa-db
    image: registry.redhat.io/rhel8/postgresql-12@sha256:be7212e938d1ef314a75aca070c28b6433cd0346704d0d3523c8ef403ff0c69e
    imagePullPolicy: IfNotPresent
    name: db
    ports:
    - containerPort: 5432
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/pgsql
      name: db
    - mountPath: /opt/app-root/src/postgresql-cfg
      name: noobaa-postgres-config-volume
    - mountPath: /init
      name: noobaa-postgres-initdb-sh-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rsgvc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: noobaa-db-pg-0
  imagePullSecrets:
  - name: noobaa-endpoint-dockercfg-h2z8w
  initContainers:
  - command:
    - /noobaa_init_files/noobaa_init.sh
    - init_postgres
    image: registry.redhat.io/ocs4/mcg-core-rhel8@sha256:ddfd0c9351019149702ab988a5c12627f63bffa7138a907d0785e87dd21313b3
    imagePullPolicy: IfNotPresent
    name: init
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/pgsql
      name: db
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rsgvc
      readOnly: true
  - command:
    - sh
    - -x
    - /init/initdb.sh
    env:
    - name: POSTGRESQL_DATABASE
      value: nbcore
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: noobaa-db
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: noobaa-db
    image: registry.redhat.io/rhel8/postgresql-12@sha256:be7212e938d1ef314a75aca070c28b6433cd0346704d0d3523c8ef403ff0c69e
    imagePullPolicy: IfNotPresent
    name: initialize-database
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
      runAsGroup: 0
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/pgsql
      name: db
    - mountPath: /init
      name: noobaa-postgres-initdb-sh-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rsgvc
      readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000660000
    runAsGroup: 0
    runAsUser: 10001
    seLinuxOptions:
      level: s0:c26,c5
  serviceAccount: noobaa-endpoint
  serviceAccountName: noobaa-endpoint
  subdomain: noobaa-db-pg
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: db-noobaa-db-pg-0
  - configMap:
      defaultMode: 420
      name: noobaa-postgres-config
    name: noobaa-postgres-config-volume
  - configMap:
      defaultMode: 420
      name: noobaa-postgres-initdb-sh
    name: noobaa-postgres-initdb-sh-volume
  - name: kube-api-access-rsgvc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-18T13:59:30Z"
    message: '0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Guaranteed
