apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2022-05-18T17:11:46Z"
  generation: 1
  labels:
    operators.coreos.com/odf-operator.openshift-storage: ""
  name: odf-operator
  namespace: openshift-storage
  resourceVersion: "35200"
  uid: 911b6243-fa05-4776-9fc1-4d956dcedad6
spec:
  channel: stable-4.10
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-operator.v4.10.2
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: certified-operators
      namespace: openshift-marketplace
      resourceVersion: "29722"
      uid: 8b2fdad1-fc3c-4db5-aee2-942341ed6f14
    healthy: true
    lastUpdated: "2022-05-18T17:11:46Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: community-operators
      namespace: openshift-marketplace
      resourceVersion: "31844"
      uid: a2cf39d0-9cfd-4339-9231-0b1f8ea5f33e
    healthy: true
    lastUpdated: "2022-05-18T17:11:46Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-marketplace
      namespace: openshift-marketplace
      resourceVersion: "31745"
      uid: 0d804e71-3544-49cd-844c-b4a26c5925bd
    healthy: true
    lastUpdated: "2022-05-18T17:11:46Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-operators
      namespace: openshift-marketplace
      resourceVersion: "31899"
      uid: e8a4a324-8254-40f6-a2b2-2c3da45809b9
    healthy: true
    lastUpdated: "2022-05-18T17:11:46Z"
  conditions:
  - lastTransitionTime: "2022-05-18T17:11:46Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  currentCSV: odf-operator.v4.10.2
  installPlanGeneration: 1
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-h44mz
    namespace: openshift-storage
    resourceVersion: "32608"
    uid: 80f6fe35-d2c7-449b-902a-c96161e6d1f1
  installedCSV: odf-operator.v4.10.2
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-h44mz
    uuid: 80f6fe35-d2c7-449b-902a-c96161e6d1f1
  lastUpdated: "2022-05-18T17:13:01Z"
  state: AtLatestKnown
